### ISSUE TITLE
Jump table case flags are incorrectly extended to 64-bit on Windows

### ISSUE THREAD

**Issue by yarjor** [radare/radare2#11532]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 Home, 64-bit
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32, x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19456 @ windows-x86-32 git.2.9.0-105-ge18c16e71; commit: e18c16e71460b1be9a31bd27a4f6e980eaccdf41 build: Fri 09/14/2018__23:59:40.98

### Expected behavior
When analyzing a jump table, all the resulting flags should be placed in the correct address.

### Actual behavior
All the case flags except for the default case are incorrectly extended to 64-bit. For example, if my case was on address 0x4057f2, the flag will be placed on address 0x4057f200000000, which of course does not exist. 

### Steps to reproduce the behavior 
- Bug is reproduceable on both following binaries:
[Lab06-03.zip](https://github.com/radare/radare2/files/2385625/Lab06-03.zip)
[case_test.zip](https://github.com/radare/radare2/files/2385636/case_test.zip)
- Analyze with aaa
- Start switch case and default case flags will be placed correctly, the rest will be placed in high non-existent addresses.

### Additional Logs, screenshots, source-code,  configuration dump, ...

I have tested for this issue with the same binary (Lab06-03.exe) on both the aforementioned windows setup and a linux setup (arch-linux, 0x86_64, version radare2 3.0.0-git 19452 @ linux-x86-64 git.2.9.0-102-g7ecbaafed commit: 7ecbaafed37935d990ea55844b01c0a1e6809465 build: 2018-09-14__15:07:41). The issue did not happen on linux. Comparison between `f` results on both:

#### Windows
```
[0x00401130]>  f~401153
0x40115a00000000 1 case.0x401153.0
0x40116c00000000 1 case.0x401153.1
0x40117f00000000 1 case.0x401153.2
0x40118c00000000 1 case.0x401153.3
0x4011d400000000 1 case.0x401153.4
0x00401153 1 switch.0x00401153
```

#### Linux
```
[0x00401130]> f~401153
0x0040115a 1 case.0x401153.0
0x0040116c 1 case.0x401153.1
0x0040117f 1 case.0x401153.2
0x0040118c 1 case.0x401153.3
0x004011d4 1 case.0x401153.4
0x00401153 1 switch.0x00401153
```

**Comment by radare** [comment]
That seems like a bug in a format string passing invalid size or casting to the wrong size. Can probably be fixed by just fixing compilation warnings

**Comment by pelijah** [comment]
I am not sure is it bug or not but maybe related https://github.com/radare/radare2/pull/11542. I can't test it becasue I don't want download malware.

**Comment by yarjor** [comment]
you can test with case_test.zip, it is not malware - I wrote it simply for testing whether it happens only with the specific exe.
Source code:
```c
#include <stdio.h>

int main(int argc) {
   switch(argc) {
      case 1   :
         printf("No args supplied!");
         break;
      case 2   :
         printf("One arg supplied!");
         break;
      case 3   :
         printf("Two args supplied!");
         break;
      case 4   :
         printf("Three args supplied!");
         break;
      case 15   :
         printf("Why would you need 15 args...?");
         break;
      default  :
         printf("Too many args to count...");
         break;
   }
   return 0;
}
```

**Comment by pelijah** [comment]
@yarjor r2 from master:
```
0x00401630 1 case.0x4015e8.0
0x004015ea 1 case.0x4015e8.1
0x004015f8 1 case.0x4015e8.2
0x00401606 1 case.0x4015e8.3
0x00401614 1 case.0x4015e8.4
0x004015e8 1 switch.0x004015e8
0x00401630 1 case.default.0x401630
0x00401be0 1 case.0x401b2f.0
0x00401b31 1 case.0x401b2f.1
0x00401b94 1 case.0x401b2f.2
0x00401ba0 1 case.0x401b2f.3
0x00401bb0 1 case.0x401b2f.4
0x00401b2f 1 switch.0x00401b2f
0x00401be0 1 case.default.0x401be0
```

**Comment by yarjor** [comment]
Was this on windows or linux? cause it worked fine on linux for me but not on windows...
I have pulled and compiled again right now and it still happens.
Version now:
radare2 3.0.0-git 19498 @ windows-x86-32 git.2.9.0-143-gc2cd5fd3e
commit: c2cd5fd3ea0d0e0319bee9bee0dcaa6bf8ef6b89 build: Mon 09/17/2018__22:31:53.77
```
0x401be000000000 1 case.0x401b2f.0
0x401b3100000000 1 case.0x401b2f.1
0x401b9400000000 1 case.0x401b2f.2
0x401ba000000000 1 case.0x401b2f.3
0x401bb000000000 1 case.0x401b2f.4
0x00401be0 1 case.default.0x401be0
```

**Comment by pelijah** [comment]
Bug is reproduced only on x86 version.

**Comment by radare** [comment]
this should be easy to fix, can you try with debian-32bit + ubsan or just valgrind?

**Comment by pelijah** [comment]
I didn't test it on Linux. Only on Windows.

**Comment by radare** [comment]
I have the fix. Ill commit in few mins
