### ISSUE TITLE
pd -x is broken again

### ISSUE THREAD

**Issue by radare** [radare/radare2#2149]
* shows lot of warning messags (should display none)
* breaks the webui scrolling
* pdj can take too much time

**Comment by crowell** [comment]
wtf when did this happen? can someone bisect it?

**Comment by crowell** [comment]
ok it is just printing some garbage due to some new logging `eprintf` stuff.
@radare what do you think of just silencing the error print if we are doing bwdisassemble?

**Comment by radare** [comment]
See my last commit, there were some issues with thw generated json, i reverted the cosarara change bwcause it was breaking it (comments must be exported to base64).

**Comment by crowell** [comment]
@radare right, because of the nature of the backwards disassembly (on things like x86 with variable width instructions) we're going to get what is now marked as a "disassemble error"
I think we should probably just remove that eprintf all together.

**Comment by radare** [comment]
if you look at the webui, you’ll see lot of var undefined = undefined, which is a regression. anybody knows when this happened? i have also removed the cosarara’s patch because it broke the JSON by trying to add autocomments in the webui disasm. this should be fixed too

**Comment by radare** [comment]
Related https://github.com/radare/radare2/issues/2223

**Comment by crowell** [comment]
is this still broken, it seems to be wroking?

**Comment by Maijin** [comment]
@crowell still broken try `wx 90909090909090909090 ; s 10 ; pd -10`

**Comment by crowell** [comment]
`pd -x` fixed, `pi -x` is broken hardcore

**Comment by Maijin** [comment]
p8, pB, ...

**Comment by crowell** [comment]
yeah, I know -__- I'll work on fixing them

On Sun, Apr 12, 2015 at 3:24 PM, Maijin <notifications@github.com> wrote:

> p8, pB, ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radare/radare2/issues/2149#issuecomment-92105518>.
>



-- 
Jeff Crowell
https://github.com/crowell

**Comment by radare** [comment]
Cool! Thanks

**Comment by radare** [comment]
imho, those p8,pB, ... should go in a separate issue, pd seems correct now

**Comment by jvoisin** [comment]
I opened new issues for them :)
