### ISSUE TITLE
Installation problem on Lubuntu 15.04 64-bit

### ISSUE THREAD

**Issue by sylvainpelissier** [radare/radare2#3393]
I tried to install radare2 on Lubuntu 15.04 64-bit. I downloaded the zip archive and I executed the following command:

> sudo sys/install.sh

but I got the following error:

> ...
> ar: creating libsdb.a
> cp: ‘sdb/src/libsdb.a’ and ‘sdb/src/libsdb.a’ are the same file
> Makefile:31: recipe for target 'all' failed
> make: **\* [all] Error 2
> Oops

 I cannot figure out what I did wrong.

**Comment by radare** [comment]
Sys/install dowsnt needs sudo to run.

Never tried the zip. But zips are not the way to get souce stuff in unixland. Use git, but the tarball should work too. Anyway my bet is that it fails because of missing capstone because it is an external dependency that.

**Comment by sylvainpelissier** [comment]
Thank you for your answer. Usually I used the git installation but this machine is not connected to Internet. That's why I'm using the zip. I've install capstone but I still have the same error. Is there any other dependencies which could create such error ?

**Comment by ret2libc** [comment]
I get this error too sometimes. A 'make' should fix it. There's probably
something wrong with sys/install
Il 30/set/2015 05:07 PM, "Sylvain Pelissier" <notifications@github.com> ha
scritto:

**Comment by radare** [comment]
I never got this. But a full log may help. Also, if a later make fixes the build can be a race condition

**Comment by CoolOppo** [comment]
I believe this happened to me when I had a custom `CFLAGS` set. If you're not sure, just run `echo $CFLAGS`. If it outputs anything, just run `export CFLAGS=''` to delete it.

**Comment by radare** [comment]
Or even better 'unset CFLAGS'

**Comment by sylvainpelissier** [comment]
In my case the "make" does not solve the problem since it will try to launch git to get capstone remotely even if it is already installed:

>"/bin/sh" capstone.sh "https://github.com/aquynh/capstone.git" "next" "839f06e855a38499de82b3014101fa1706fba994" ""
>capstone.sh: 11: capstone.sh: git: not found
>capstone.sh: 13: cd: can't cd to capstone
>Makefile:206: recipe for target 'capstone-sync' failed
>make[1]: *** [capstone-sync] Error 1
>make[1]: Leaving directory '/home/sylvain/softwares/radare2-master/shlr'
>Makefile:31: recipe for target 'all' failed
>make: *** [all] Error 2
>sylvain@sylvain-OptiPlex-755:~/softwares/radare2-master$ git
>The program 'git' is currently not installed. You can install it by typing:
>sudo apt-get install git
>You will have to enable the component called 'main'

I have nothing in CLFAGS.

**Comment by radare** [comment]
this script shouldbe called only when capstone is not found in system, can you check the value of USE_CAPSTONE in config-user.mk ?

the checkout script fails because you dont have git installed

**Comment by sylvainpelissier** [comment]
for the capstone section I have:

># capstone
>USE_CAPSTONE=0
>ifeq ($(USE_CAPSTONE),1)
>CAPSTONE_CFLAGS=
>CAPSTONE_LDFLAGS=
>else
>CAPSTONE_CFLAGS=
>CAPSTONE_LDFLAGS=
>endif

**Comment by CoolOppo** [comment]
I figured there was a much better way of doing that.

**Comment by radare** [comment]
?

**Comment by sylvainpelissier** [comment]
I found a quick and dirty fix by copying the **capstone** folder from another install of radare2 to the **shlr** folder and then the installation finished properly. However I was not able to change config-user.mk successfully so it uses the local install of capstone.

**Comment by radare** [comment]
did you tried with —with-syscapstone ?

**Comment by sylvainpelissier** [comment]
It gives the same error.

**Comment by radare** [comment]
the error clearly shows that it cannot git clone because there's no such command. did you tried installing git?, do you have capstone installed in system?

**Comment by sylvainpelissier** [comment]
Even when with git installed it tries to connect to the server to download capstone. I installed capstone using the package manager of the distribution.
