### ISSUE TITLE
User defined labels do not replace addresses in 68k disassembly

### ISSUE THREAD

**Issue by cr1901** [radare/radare2#4304]
Mirroring issue #3841 that I opened back in December, I am having trouble getting the 68k backend to honor manual labels that I create in the disassembled output. The use case was to fill in the Sega Genesis I/O addr space with easy-to-read names, such as the z80 Bus Request register at 0xa11100, as shown below:

```
C:\W2CUTILS\radare2-w32-0.10.2-git>radare2.exe -e -a68k "F:\Legacy\Genesis\ROMS\
ShiningInTheDarkne.2103\ShiningInTheDarkne2103.bin"
Copyright: SEGA MEGA DRIVE (C)SEGA 1991.JUL
DomesticName: SHINING AND         THE DARKNESS
OverseasName: SHINING IN          THE DARKNESS
ProductCode: GM MK-1310  00
Checksum: 0x0321
Peripherials: J
SramCode:  UE
ModemCode:  UE
CountryCode:  UE
 -- nothing personal, just bitness
[0x00000200]> s 0x354
[0x00000354]> f sym.z80BusReq @ 0x00a11100
[0x00000354]> pd
            ;-- Reset:
            0x00000354      4e71           nop
            0x00000356      4e71           nop
            0x00000358      4e71           nop
            0x0000035a      4e71           nop
            0x0000035c      4e71           nop
            0x0000035e      4e71           nop
            0x00000360      4e71           nop
            0x00000362      4e71           nop
            0x00000364      4e71           nop
            0x00000366      4e71           nop
            0x00000368      4e71           nop
            0x0000036a      4e71           nop
        ,=< 0x0000036c      6000030a       bra.w 0x678
        |   0x00000370      4ff900fffff0   lea 0xfffff0.l,sp
       ,==< 0x00000376      4eb9000011b2   jsr 0x11b2.l
      ,===< 0x0000037c      61005f32       bsr.w 0x62b0
      |||   0x00000380      4eba01ee       jsr 0x570(pc)
      |||   0x00000384      4e71           nop
     ,====< 0x00000386      4ef900002ebe   jmp 0x2ebe.l
     ||||   ;-- BusErr:
     ||||   ;-- InvOpCode:
     ||||   0x0000038c      23ef000a00ff.  move.l 0xa(sp),0xff3a54.l
     ||||   0x00000394      48e7fffe       movem.l d0-d7/a0-a6,-(sp)
    ,=====< 0x00000398      4eb900018034   jsr 0x18034.l
    |||||   0x0000039e      303c0200       move.w 0x200,d0
   ,======< 0x000003a2      4eb900018018   jsr 0x18018.l
   ||||||   0x000003a8      4cdf7fff       movem.l (sp)+,d0-d7/a0-a6
  ,=======< 0x000003ac      60000022       bra.w 0x3d0
  |||||||   ;-- DivBy0:
  |||||||   ;-- Check:
  |||||||   ;-- TrapV:
  |||||||   ;-- GPF:
  |||||||   ;-- Trace:
  |||||||   ;-- Reserv0:
  |||||||   ;-- Reserv1:
  |||||||   ;-- Reserv2:
  |||||||   ;-- Reserv3:
  |||||||   ;-- Reserv4:
  |||||||   ;-- BadInt:
  |||||||   ;-- Reserv10:
  |||||||   ;-- Reserv11:
  |||||||   ;-- Reserv12:
  |||||||   ;-- Reserv13:
  |||||||   ;-- Reserv14:
  |||||||   ;-- Reserv15:
  |||||||   ;-- Reserv16:
  |||||||   ;-- Reserv17:
  |||||||   ;-- BadIRQ:
  |||||||   ;-- IRQ1:
  |||||||   ;-- EXT:
  |||||||   ;-- IRQ3:
  |||||||   ;-- HBLANK:
  |||||||   ;-- VBLANK:
  |||||||   ;-- Trap7:
  |||||||   ;-- Trap8:
  |||||||   ;-- Trap9:
  |||||||   ;-- Trap10:
  |||||||   ;-- Trap11:
  |||||||   ;-- Trap12:
  |||||||   ;-- Trap13:
  |||||||   ;-- Trap14:
  |||||||   ;-- Trap15:
  |||||||   ;-- Reserv30:
  |||||||   ;-- Reserv31:
  |||||||   ;-- Reserv32:
  |||||||   ;-- Reserv33:
  |||||||   ;-- Reserv34:
  |||||||   ;-- Reserv35:
  |||||||   ;-- Reserv36:
  |||||||   ;-- Reserv37:
  |||||||   ;-- Reserv38:
  |||||||   ;-- Reserv39:
  |||||||   ;-- Reserv3A:
  |||||||   ;-- Reserv3B:
  |||||||   ;-- Reserv3C:
  |||||||   ;-- Reserv3D:
  |||||||   ;-- Reserv3E:
  |||||||   ;-- Reserv3F:
  |||||||   0x000003b0      23ef000200ff.  move.l 0x2(sp),0xff3a54.l
  |||||||   0x000003b8      48e7fffe       movem.l d0-d7/a0-a6,-(sp)
  ========< 0x000003bc      4eb900018034   jsr 0x18034.l
  |||||||   0x000003c2      303c0200       move.w 0x200,d0
  ========< 0x000003c6      4eb900018018   jsr 0x18018.l
  |||||||   0x000003cc      4cdf7fff       movem.l (sp)+,d0-d7/a0-a6
  `-------> 0x000003d0      4e71           nop
   ||||||   0x000003d2      4e71           nop
  ,=======< 0x000003d4      60fa           bra.b 0x3d0
  |||||||   ;-- Trap0:
  |||||||   0x000003d6      4e71           nop
  ========< 0x000003d8      60fc           bra.b sym.Trap0
  |||||||   ;-- Trap1:
  |||||||   0x000003da      33fc010000a1.  move.w section.header,0xa11100.l
  |||||||   0x000003e2      0839000000a1.  btst 0,0xa11100.l
  ========< 0x000003ea      66f6           bne.b 0x3e2
  |||||||   0x000003ec      0c0000fb       cmpi.b -0x5,d0
  ========< 0x000003f0      663a           bne.b 0x42c
  |||||||   0x000003f2      4a3900ff001b   tst.b 0xff001b.l
  ========< 0x000003f8      671e           beq.b 0x418
  |||||||   0x000003fa      48e70180       movem.l d7/a0,-(sp)
  |||||||   0x000003fe      41f900ff001c   lea 0xff001c.l,a0
  |||||||   0x00000404      7e08           moveq 0x8,d7
  |||||||   0x00000406      10e80001       move.b 0x1(a0),(a0)+
  |||||||   0x0000040a      51cffffa       dbf d7,0x406
  |||||||   0x0000040e      4cdf0180       movem.l (sp)+,d7/a0
  |||||||   0x00000412      533900ff001b   subq.b 0x1,0xff001b.l
  --------> 0x00000418      13f900ff001c.  move.b 0xff001c.l,0xa01fff.l
  |||||||   0x00000422      33fc000000a1.  move.w 0,0xa11100.l
  |||||||   0x0000042a      4e73           rte
  --------> 0x0000042c      0c0000fd       cmpi.b -0x3,d0
  ========< 0x00000430      6510           bcs.b 0x442
  |||||||   0x00000432      13c000a01fff   move.b d0,0xa01fff.l
  |||||||   0x00000438      33fc000000a1.  move.w 0,0xa11100.l
  |||||||   0x00000440      4e73           rte
  --------> 0x00000442      0c0000f0       cmpi.b -0x10,d0
  ========< 0x00000446      6610           bne.b 0x458
  |||||||   0x00000448      103900a01283   move.b 0xa01283.l,d0
  |||||||   0x0000044e      33fc000000a1.  move.w 0,0xa11100.l
  |||||||   0x00000456      4e73           rte
[0x00000354]>
```

I would expect, for instance, address 0x0000044e to be `move.w 0, sym.z80BusReq.l` and not `move.w 0,0xa11100.l`. The only symbols that properly replace addresses are those that are autodetected when the ROM is loaded (address 0x000003d8 correctly references sym.Trap0).

The solution to issue #3841 was to include "." in the labels. Yet when I do so here, nothing happens. Is this perhaps another Genesis/68k backend bug?

**Comment by Maijin** [comment]
Did you also try with m68k.cs ?

**Comment by cr1901** [comment]
How do I specify that? (Incidentally, radare2 autodetects this is 68k if I omit the `-a` flag)

**Comment by Maijin** [comment]
m68k is one engine for 68000, m68k.cs is another one using capstone

**Comment by Maijin** [comment]
just use -a m68k.cs or -a m68k

**Comment by Maijin** [comment]
Please see https://github.com/radare/radare2/issues/3617

**Comment by cr1901** [comment]
Same output:
```
C:\W2CUTILS\radare2-w32-0.10.2-git>radare2.exe -e -a m68k.cs "F:\Legacy\Genesis\
ROMS\ShiningInTheDarkne.2103\ShiningInTheDarkne2103.bin"
Copyright: SEGA MEGA DRIVE (C)SEGA 1991.JUL
DomesticName: SHINING AND         THE DARKNESS
OverseasName: SHINING IN          THE DARKNESS
ProductCode: GM MK-1310  00
Checksum: 0x0321
Peripherials: J
SramCode:  UE
ModemCode:  UE
CountryCode:  UE
 -- Assemble opcodes with the 'a' and 'A' keys in visual mode, which are binding
s to the 'wa' and 'wA' commands
[0x00000200]> s 0x354
[0x00000354]> f sym.z80BusReq @ 0x00a11100
[0x00000354]> pd
            ;-- Reset:
            0x00000354      4e71           nop
            0x00000356      4e71           nop
            0x00000358      4e71           nop
            0x0000035a      4e71           nop
            0x0000035c      4e71           nop
            0x0000035e      4e71           nop
            0x00000360      4e71           nop
            0x00000362      4e71           nop
            0x00000364      4e71           nop
            0x00000366      4e71           nop
            0x00000368      4e71           nop
            0x0000036a      4e71           nop
        ,=< 0x0000036c      6000030a       bra.w 0x678
        |   0x00000370      4ff900fffff0   lea 0xfffff0.l,sp
       ,==< 0x00000376      4eb9000011b2   jsr 0x11b2.l
      ,===< 0x0000037c      61005f32       bsr.w 0x62b0
      |||   0x00000380      4eba01ee       jsr 0x570(pc)
      |||   0x00000384      4e71           nop
     ,====< 0x00000386      4ef900002ebe   jmp 0x2ebe.l
     ||||   ;-- BusErr:
     ||||   ;-- InvOpCode:
     ||||   0x0000038c      23ef000a00ff.  move.l 0xa(sp),0xff3a54.l
     ||||   0x00000394      48e7fffe       movem.l d0-d7/a0-a6,-(sp)
    ,=====< 0x00000398      4eb900018034   jsr 0x18034.l
    |||||   0x0000039e      303c0200       move.w 0x200,d0
   ,======< 0x000003a2      4eb900018018   jsr 0x18018.l
   ||||||   0x000003a8      4cdf7fff       movem.l (sp)+,d0-d7/a0-a6
  ,=======< 0x000003ac      60000022       bra.w 0x3d0
  |||||||   ;-- DivBy0:
  |||||||   ;-- Check:
  |||||||   ;-- TrapV:
  |||||||   ;-- GPF:
  |||||||   ;-- Trace:
  |||||||   ;-- Reserv0:
  |||||||   ;-- Reserv1:
  |||||||   ;-- Reserv2:
  |||||||   ;-- Reserv3:
  |||||||   ;-- Reserv4:
  |||||||   ;-- BadInt:
  |||||||   ;-- Reserv10:
  |||||||   ;-- Reserv11:
  |||||||   ;-- Reserv12:
  |||||||   ;-- Reserv13:
  |||||||   ;-- Reserv14:
  |||||||   ;-- Reserv15:
  |||||||   ;-- Reserv16:
  |||||||   ;-- Reserv17:
  |||||||   ;-- BadIRQ:
  |||||||   ;-- IRQ1:
  |||||||   ;-- EXT:
  |||||||   ;-- IRQ3:
  |||||||   ;-- HBLANK:
  |||||||   ;-- VBLANK:
  |||||||   ;-- Trap7:
  |||||||   ;-- Trap8:
  |||||||   ;-- Trap9:
  |||||||   ;-- Trap10:
  |||||||   ;-- Trap11:
  |||||||   ;-- Trap12:
  |||||||   ;-- Trap13:
  |||||||   ;-- Trap14:
  |||||||   ;-- Trap15:
  |||||||   ;-- Reserv30:
  |||||||   ;-- Reserv31:
  |||||||   ;-- Reserv32:
  |||||||   ;-- Reserv33:
  |||||||   ;-- Reserv34:
  |||||||   ;-- Reserv35:
  |||||||   ;-- Reserv36:
  |||||||   ;-- Reserv37:
  |||||||   ;-- Reserv38:
  |||||||   ;-- Reserv39:
  |||||||   ;-- Reserv3A:
  |||||||   ;-- Reserv3B:
  |||||||   ;-- Reserv3C:
  |||||||   ;-- Reserv3D:
  |||||||   ;-- Reserv3E:
  |||||||   ;-- Reserv3F:
  |||||||   0x000003b0      23ef000200ff.  move.l 0x2(sp),0xff3a54.l
  |||||||   0x000003b8      48e7fffe       movem.l d0-d7/a0-a6,-(sp)
  ========< 0x000003bc      4eb900018034   jsr 0x18034.l
  |||||||   0x000003c2      303c0200       move.w 0x200,d0
  ========< 0x000003c6      4eb900018018   jsr 0x18018.l
  |||||||   0x000003cc      4cdf7fff       movem.l (sp)+,d0-d7/a0-a6
  `-------> 0x000003d0      4e71           nop
   ||||||   0x000003d2      4e71           nop
  ,=======< 0x000003d4      60fa           bra.b 0x3d0
  |||||||   ;-- Trap0:
  |||||||   0x000003d6      4e71           nop
  ========< 0x000003d8      60fc           bra.b sym.Trap0
  |||||||   ;-- Trap1:
  |||||||   0x000003da      33fc010000a1.  move.w section.header,0xa11100.l
  |||||||   0x000003e2      0839000000a1.  btst 0,0xa11100.l
  ========< 0x000003ea      66f6           bne.b 0x3e2
  |||||||   0x000003ec      0c0000fb       cmpi.b -0x5,d0
  ========< 0x000003f0      663a           bne.b 0x42c
  |||||||   0x000003f2      4a3900ff001b   tst.b 0xff001b.l
  ========< 0x000003f8      671e           beq.b 0x418
  |||||||   0x000003fa      48e70180       movem.l d7/a0,-(sp)
  |||||||   0x000003fe      41f900ff001c   lea 0xff001c.l,a0
  |||||||   0x00000404      7e08           moveq 0x8,d7
  |||||||   0x00000406      10e80001       move.b 0x1(a0),(a0)+
  |||||||   0x0000040a      51cffffa       dbf d7,0x406
  |||||||   0x0000040e      4cdf0180       movem.l (sp)+,d7/a0
  |||||||   0x00000412      533900ff001b   subq.b 0x1,0xff001b.l
  --------> 0x00000418      13f900ff001c.  move.b 0xff001c.l,0xa01fff.l
  |||||||   0x00000422      33fc000000a1.  move.w 0,0xa11100.l
  |||||||   0x0000042a      4e73           rte
  --------> 0x0000042c      0c0000fd       cmpi.b -0x3,d0
  ========< 0x00000430      6510           bcs.b 0x442
  |||||||   0x00000432      13c000a01fff   move.b d0,0xa01fff.l
  |||||||   0x00000438      33fc000000a1.  move.w 0,0xa11100.l
  |||||||   0x00000440      4e73           rte
  --------> 0x00000442      0c0000f0       cmpi.b -0x10,d0
  ========< 0x00000446      6610           bne.b 0x458
  |||||||   0x00000448      103900a01283   move.b 0xa01283.l,d0
  |||||||   0x0000044e      33fc000000a1.  move.w 0,0xa11100.l
  |||||||   0x00000456      4e73           rte
[0x00000354]>
```

**Comment by Maijin** [comment]
Do you have any binaries that can be shared [no license...] to create the tests ?

**Comment by cr1901** [comment]
I could share my Shining In The Darkness ROM, but that's of questionable legality :P...

**Comment by Maijin** [comment]
yes, we can't use this one, any PD Rom with this behaviour ?

**Comment by cr1901** [comment]
I'll make a test ROM tonight/tomorrow and duplicate the problem.

**Comment by radare** [comment]
that's because libr/parse only looks for `0xa11100` instead of `0xa11100.l`. also there's no m68k-specific parse plugin, and this syntax is a bit weird to consider it generic. what do this `.l` means? can we remove it?

**Comment by cr1901** [comment]
@radare Traditional 68k assemblers expect instruction mnemonics and operands to be qualified with either `.b`, `.w`, or `.l` to indicate their width, so the assembler can determine which instruction encoding to use.

**Comment by radare** [comment]
uhm.. this replacement works for me. im using the m68k plugin, not the capstone one and loading the rom found in r2r/bins/smd which is an opensource game for megadrive

**Comment by radare** [comment]
see https://github.com/radare/radare2-regressions/commit/fdc3836bbc765a7a84f2f3a3ac5aa149498488fd

**Comment by Maijin** [comment]
```
_dA_  16 32      m68k        BSD     Motorola 68000
_dA_  32         m68k.cs     BSD     Capstone M68K disassembler
```

I don't see m68k.gnu

**Comment by radare** [comment]
So here's the first gnu/capstone inconsistency:

```
+++ /tmp/r2-regressions//m68k-out.XXv56i        2016-03-16 12:27:54.199337726 +0100
@@ -1,4 +1,4 @@
 move.w 0x100, 0xa10000.l
+move.w #0x100, 0xaaaaaaaa.l
 move.w 0x100, 0xa10000.l
-move.w 0x100, foo.bar
-move.w 0x100, foo.bar
+move.w #0x100, 0xaaaaaaaa.l

```

**Comment by radare** [comment]
If you wanna get better m68k refs and analysis you should be implementing the ESIL expressions for each instruction

**Comment by radare** [comment]
Shall we use capstone by default on m68k?

**Comment by radare** [comment]
(im asking because i dont really RE m68k code.. so you can have a better opinion on this)

**Comment by radare** [comment]
Capstone seems to disassemble this instruction different than GNU:
```
-move.w 0x100, 0xa10000.l
+move.w 0x100, 0xaaaaaaaa.l
```

bytes: 33fc0100

**Comment by radare** [comment]
I have updated the tests and commited some changes, so imho it is working now. please confirm

**Comment by Maijin** [comment]
@emoon

**Comment by emoon** [comment]
I think the difference here is because the instruction ```33fc0100``` isn't actually legal. To generate this instruction

```
move.w 0x100, 0xa10000.l
```

The following bytes are needed
```
33 FC 01 00 00 A1 00 00
```

Which can be verified by https://www.onlinedisassembler.com and the output from capstone is

```
Platform: M68K
Code:0x33 0xfc 0x01 0x00 0x00 0xa1 0x00 0x00
Disasm:
0x1000:	move.w	#$100, $a10000.l
```

**Comment by cr1901** [comment]
I was pulling my hair out trying to decode this instruction (unsuccessfully) earlier and reached the same conclusion. Something isn't right here... (it's also possible that the tables I'm using suck too)

**Comment by emoon** [comment]
Also Genesis/Megadrive uses a "pure" m68k right? (Meaning that it doesn't have any extensions or similar to the instruction set)

**Comment by cr1901** [comment]
I believe it's a pure m68k.
Use the capstone backend for now. Was the GNU backend written specifically for r2?

**Comment by emoon** [comment]
Ok I have investigate this a bit more

https://www.onlinedisassembler.com/odaweb/YU6DCsrO/0

With these bytes

```
4C DF 01 80 53 39 00 FF 00 1B 13 F9 00 FF 00 1C 00 A0 1F FF 33 FC 00 00 00 A1 11 00 4E 73
```

Capstone will output

0x1000:	movem.l	(a7)+, d7/a0
0x1004:	subq.b	#$1, $ff001b.l
0x100a:	move.b	$ff001c.l, $a01fff.l
0x1014:	move.w	#$0, $a11100.l
0x101c:	rte
```

Which is the some as onlinedisasm. What got me a bit confused above is the ```13f900ff001c.``` which is cut off.

**Comment by cr1901** [comment]
@radare2: Negative. Did not fix the issue on my end.

GNU engine:
```
William@WILLIAM-THINK C:\msys64\home\William\src\radare2\radare2-w32-0.10.2-git
> radare2.exe -a m68k F:\Legacy\Genesis\ROMS\ShiningInTheDarkne.2103\ShiningInTheDarkne2103.bin
Copyright: SEGA MEGA DRIVE (C)SEGA 1991.JUL
DomesticName: SHINING AND         THE DARKNESS
OverseasName: SHINING IN          THE DARKNESS
ProductCode: GM MK-1310  00
Checksum: 0x0321
Peripherials: J
SramCode:  UE
ModemCode:  UE
CountryCode:  UE
 -- THE CAKE IS A PIE
[0x00000200]> s 0x354
[0x00000354]> f sym.z80BusReq @ 0x00a11100
[0x00000354]> pd
            ;-- Reset:
            0x00000354      4e71           nop
            0x00000356      4e71           nop
            0x00000358      4e71           nop
            0x0000035a      4e71           nop
            0x0000035c      4e71           nop
            0x0000035e      4e71           nop
            0x00000360      4e71           nop
            0x00000362      4e71           nop
            0x00000364      4e71           nop
            0x00000366      4e71           nop
            0x00000368      4e71           nop
            0x0000036a      4e71           nop
        ,=< 0x0000036c      6000030a       bra.w 0x678
        |   0x00000370      4ff900fffff0   lea 0xfffff0.l, sp
       ,==< 0x00000376      4eb9000011b2   jsr 0x11b2.l
      ,===< 0x0000037c      61005f32       bsr.w 0x62b0
      |||   0x00000380      4eba01ee       jsr 0x570(pc)
      |||   0x00000384      4e71           nop
     ,====< 0x00000386      4ef900002ebe   jmp 0x2ebe.l
     ||||   ;-- BusErr:
     ||||   ;-- InvOpCode:
     ||||   0x0000038c      23ef000a00ff.  move.l 0xa(sp), 0xff3a54.l
     ||||   0x00000394      48e7fffe       movem.l d0-d7/a0-a6, -(sp)
    ,=====< 0x00000398      4eb900018034   jsr 0x18034.l
    |||||   0x0000039e      303c0200       move.w 0x200, d0
   ,======< 0x000003a2      4eb900018018   jsr 0x18018.l
   ||||||   0x000003a8      4cdf7fff       movem.l (sp)+, d0-d7/a0-a6
  ,=======< 0x000003ac      60000022       bra.w 0x3d0
  |||||||   ;-- DivBy0:
  |||||||   ;-- Check:
  |||||||   ;-- TrapV:
  |||||||   ;-- GPF:
  |||||||   ;-- Trace:
  |||||||   ;-- Reserv0:
  |||||||   ;-- Reserv1:
  |||||||   ;-- Reserv2:
  |||||||   ;-- Reserv3:
  |||||||   ;-- Reserv4:
  |||||||   ;-- BadInt:
  |||||||   ;-- Reserv10:
  |||||||   ;-- Reserv11:
  |||||||   ;-- Reserv12:
  |||||||   ;-- Reserv13:
  |||||||   ;-- Reserv14:
  |||||||   ;-- Reserv15:
  |||||||   ;-- Reserv16:
  |||||||   ;-- Reserv17:
  |||||||   ;-- BadIRQ:
  |||||||   ;-- IRQ1:
  |||||||   ;-- EXT:
  |||||||   ;-- IRQ3:
  |||||||   ;-- HBLANK:
  |||||||   ;-- VBLANK:
  |||||||   ;-- Trap7:
  |||||||   ;-- Trap8:
  |||||||   ;-- Trap9:
  |||||||   ;-- Trap10:
  |||||||   ;-- Trap11:
  |||||||   ;-- Trap12:
  |||||||   ;-- Trap13:
  |||||||   ;-- Trap14:
  |||||||   ;-- Trap15:
  |||||||   ;-- Reserv30:
  |||||||   ;-- Reserv31:
  |||||||   ;-- Reserv32:
  |||||||   ;-- Reserv33:
  |||||||   ;-- Reserv34:
  |||||||   ;-- Reserv35:
  |||||||   ;-- Reserv36:
  |||||||   ;-- Reserv37:
  |||||||   ;-- Reserv38:
  |||||||   ;-- Reserv39:
  |||||||   ;-- Reserv3A:
  |||||||   ;-- Reserv3B:
  |||||||   ;-- Reserv3C:
  |||||||   ;-- Reserv3D:
  |||||||   ;-- Reserv3E:
  |||||||   ;-- Reserv3F:
  |||||||   0x000003b0      23ef000200ff.  move.l 0x2(sp), 0xff3a54.l
  |||||||   0x000003b8      48e7fffe       movem.l d0-d7/a0-a6, -(sp)
  ========< 0x000003bc      4eb900018034   jsr 0x18034.l
  |||||||   0x000003c2      303c0200       move.w 0x200, d0
  ========< 0x000003c6      4eb900018018   jsr 0x18018.l
  |||||||   0x000003cc      4cdf7fff       movem.l (sp)+, d0-d7/a0-a6
  `-------> 0x000003d0      4e71           nop
   ||||||   0x000003d2      4e71           nop
  ,=======< 0x000003d4      60fa           bra.b 0x3d0
  |||||||   ;-- Trap0:
  |||||||   0x000003d6      4e71           nop
  ========< 0x000003d8      60fc           bra.b sym.Trap0
  |||||||   ;-- Trap1:
  |||||||   0x000003da      33fc010000a1.  move.w section.header, 0xa11100.l
  |||||||   0x000003e2      0839000000a1.  btst 0, 0xa11100.l
  ========< 0x000003ea      66f6           bne.b 0x3e2
  |||||||   0x000003ec      0c0000fb       cmpi.b -0x5, d0
  ========< 0x000003f0      663a           bne.b 0x42c
  |||||||   0x000003f2      4a3900ff001b   tst.b 0xff001b.l
  ========< 0x000003f8      671e           beq.b 0x418
  |||||||   0x000003fa      48e70180       movem.l d7/a0, -(sp)
  |||||||   0x000003fe      41f900ff001c   lea 0xff001c.l, a0
  |||||||   0x00000404      7e08           moveq 0x8, d7
  |||||||   0x00000406      10e80001       move.b 0x1(a0), (a0)+
  |||||||   0x0000040a      51cffffa       dbf d7, 0x406
  |||||||   0x0000040e      4cdf0180       movem.l (sp)+, d7/a0
  |||||||   0x00000412      533900ff001b   subq.b 0x1, 0xff001b.l
  --------> 0x00000418      13f900ff001c.  move.b 0xff001c.l, 0xa01fff.l
  |||||||   0x00000422      33fc000000a1.  move.w 0, 0xa11100.l
  |||||||   0x0000042a      4e73           rte
  --------> 0x0000042c      0c0000fd       cmpi.b -0x3, d0
  ========< 0x00000430      6510           bcs.b 0x442
  |||||||   0x00000432      13c000a01fff   move.b d0, 0xa01fff.l
  |||||||   0x00000438      33fc000000a1.  move.w 0, 0xa11100.l
  |||||||   0x00000440      4e73           rte
  --------> 0x00000442      0c0000f0       cmpi.b -0x10, d0
  ========< 0x00000446      6610           bne.b 0x458
  |||||||   0x00000448      103900a01283   move.b 0xa01283.l, d0
  |||||||   0x0000044e      33fc000000a1.  move.w 0, 0xa11100.l
  |||||||   0x00000456      4e73           rte
[0x00000354]>
```

Capstone engine:
```
William@WILLIAM-THINK C:\msys64\home\William\src\radare2\radare2-w32-0.10.2-git
> radare2.exe -a m68k.cs F:\Legacy\Genesis\ROMS\ShiningInTheDarkne.2103\ShiningInTheDarkne2103.bin
Copyright: SEGA MEGA DRIVE (C)SEGA 1991.JUL
DomesticName: SHINING AND         THE DARKNESS
OverseasName: SHINING IN          THE DARKNESS
ProductCode: GM MK-1310  00
Checksum: 0x0321
Peripherials: J
SramCode:  UE
ModemCode:  UE
CountryCode:  UE
 -- ESIL: The Aftersleep
[0x00000200]> s 0x354
[0x00000354]> f sym.z80BusReq @ 0x00a11100
[0x00000354]> pd
     ||||   ;-- Reset:
     ||||   0x00000354      4e71           nop
     ||||   0x00000356      4e71           nop
    .-----> 0x00000358      4e71           nop
    |||||   0x0000035a      4e71           nop
    |||||   0x0000035c      4e71           nop
    |||||   0x0000035e      4e71           nop
    |||||   0x00000360      4e71           nop
    |||||   0x00000362      4e71           nop
    |||||   0x00000364      4e71           nop
    |||||   0x00000366      4e71           nop
    |||||   0x00000368      4e71           nop
    |||||   0x0000036a      4e71           nop
    |||||   0x0000036c      6000030a       bra.w 0x678
    |||||   0x00000370      4ff900ff       lea.l 0xaaaaaaaa.l, a7
    |||||   0x00000374      fff0           invalid
    |||||   0x00000376      4eb90000       jsr 0xaaaaaaaa.l
    |||||   0x0000037a      11b26100       move.b (a2, d6.w), 0xaa(a0, a2.l)
    |||||   0x0000037e      5f324eba       subq.b 0x7, 0xba(a2, d4.l)
    |||||   0x00000382      01ee4e71       bset.b d0, 0x4e71(a6)
    |||||   0x00000386      4ef90000       jmp 0xaaaaaaaa.l
    |||||   ;-- BusErr:
    |||||   ;-- InvOpCode:
    |||||   0x0000038a  ~   2ebe23ef       invalid
    |||||   0x0000038e      000a00ff       invalid
    |||||   0x00000392      3a54           movea.w (a4), a5
    |||||   0x00000394      48e7fffe       movem.l d0-d7/a0-a6, -(a7)
    |||||   0x00000398      4eb90001       jsr 0xaaaaaaaa.l
    |||||   0x0000039c      8034303c       or.b 0x3c(a4, d3.w), d0
    |||||   0x000003a0      02004eb9       andi.b 0xb9, d0
    |||||   0x000003a4      00018018       ori.b 0x18, d1
    |||||   0x000003a8      4cdf7fff       movem.l (a7)+, d0-d7/a0-a6
    |||||   0x000003ac      60000022       bra.w 0x3d0
    |||||   ;-- DivBy0:
    |||||   ;-- Check:
    |||||   ;-- TrapV:
    |||||   ;-- GPF:
    |||||   ;-- Trace:
    |||||   ;-- Reserv0:
    |||||   ;-- Reserv1:
    |||||   ;-- Reserv2:
    |||||   ;-- Reserv3:
    |||||   ;-- Reserv4:
    |||||   ;-- BadInt:
    |||||   ;-- Reserv10:
    |||||   ;-- Reserv11:
    |||||   ;-- Reserv12:
    |||||   ;-- Reserv13:
    |||||   ;-- Reserv14:
    |||||   ;-- Reserv15:
    |||||   ;-- Reserv16:
    |||||   ;-- Reserv17:
    |||||   ;-- BadIRQ:
    |||||   ;-- IRQ1:
    |||||   ;-- EXT:
    |||||   ;-- IRQ3:
    |||||   ;-- HBLANK:
    |||||   ;-- VBLANK:
    |||||   ;-- Trap7:
    |||||   ;-- Trap8:
    |||||   ;-- Trap9:
    |||||   ;-- Trap10:
    |||||   ;-- Trap11:
    |||||   ;-- Trap12:
    |||||   ;-- Trap13:
    |||||   ;-- Trap14:
    |||||   ;-- Trap15:
    |||||   ;-- Reserv30:
    |||||   ;-- Reserv31:
    |||||   ;-- Reserv32:
    |||||   ;-- Reserv33:
    |||||   ;-- Reserv34:
    |||||   ;-- Reserv35:
    |||||   ;-- Reserv36:
    |||||   ;-- Reserv37:
    |||||   ;-- Reserv38:
    |||||   ;-- Reserv39:
    |||||   ;-- Reserv3A:
    |||||   ;-- Reserv3B:
    |||||   ;-- Reserv3C:
    |||||   ;-- Reserv3D:
    |||||   ;-- Reserv3E:
    |||||   ;-- Reserv3F:
    |||||   0x000003b0      23ef0002       move.l 0x2(a7), 0xaaaaaaaa.l
    |||||   0x000003b4      00ff3a54       invalid
    |||||   0x000003b8      48e7fffe       movem.l d0-d7/a0-a6, -(a7)
    |||||   0x000003bc      4eb90001       jsr 0xaaaaaaaa.l
    |||||   0x000003c0      8034303c       or.b 0x3c(a4, d3.w), d0
    |||||   0x000003c4      02004eb9       andi.b 0xb9, d0
    |||||   0x000003c8      00018018       ori.b 0x18, d1
    |||||   0x000003cc      4cdf7fff       movem.l (a7)+, d0-d7/a0-a6
    |||||   0x000003d0      4e71           nop
    |||||   0x000003d2      4e71           nop
    |||||   0x000003d4      60fa           bra.b 0x3d0
    |||||   ;-- Trap0:
    |||||   0x000003d6      4e71           nop
    |||||   0x000003d8      60fc           bra.b sym.Trap0
    |||||   ;-- Trap1:
    |||||   0x000003da      33fc0100       move.w section.header, 0xaaaaaaaa.l
    |||||   0x000003de      00a11100       ori.l 0xaaaaaaaa, -(a1)
    |||||   0x000003e2      08390000       btst.b 0x0, 0xaaaaaaaa.l
    |||||   0x000003e6      00a11100       ori.l 0xaaaaaaaa, -(a1)
    ||||`=< 0x000003ea      66f6           bne.b 0x3e2
    ||||    0x000003ec      0c0000fb       cmpi.b 0xfb, d0
    ||`===< 0x000003f0      663a           bne.b 0x42c
    || |    0x000003f2      4a3900ff       tst.b 0xaaaaaaaa.l
    || |    0x000003f6      001b671e       ori.b 0x1e, (a3)+
    ||      0x000003fa      48e70180       movem.l d7/a0, -(a7)
    ||      0x000003fe      41f900ff       lea.l 0xaaaaaaaa.l, a0
    ||      0x00000402      001c7e08       ori.b 0x8, (a4)+
    ||      0x00000406      10e80001       move.b 0x1(a0), (a0)+
    ||      0x0000040a      51cffffa       dbra d7, 0x406
    ||      0x0000040e      4cdf0180       movem.l (a7)+, d7/a0
    ||      0x00000412      533900ff       subq.b 0x1, 0xaaaaaaaa.l
    ||      0x00000416      001b13f9       ori.b 0xf9, (a3)+
    ||      0x0000041a      00ff001c       invalid
    ||      0x0000041e      00a01fff       ori.l 0xaaaaaaaa, -(a0)
    ||      0x00000422      33fc0000       move.w 0x0, 0xaaaaaaaa.l
    ||      0x00000426      00a11100       ori.l 0xaaaaaaaa, -(a1)
[0x00000354]>
```

**Comment by emoon** [comment]
This looks weird to me

GNU

```
        ,=< 0x0000036c      6000030a       bra.w 0x678
        |   0x00000370      4ff900fffff0   lea 0xfffff0.l, sp
```

And for Capstone

```
    |||||   0x0000036c      6000030a       bra.w 0x678
    |||||   0x00000370      4ff900ff       lea.l 0xaaaaaaaa.l, a7
```

It seems data is missing here?

**Comment by cr1901** [comment]
I have no idea what's going on, tbh. It's like the printed output does not match radare's internal representation. Very interesting that its choking on this ROM. I could try dumping again and seeing if I have a bad dump.

**Comment by emoon** [comment]
If I insert

```
6000030a4ff900fffff0
```

In Capstone I get

```
0x1000:	bra.w #$130c
0x1004:	lea.l   $fffff0.l, a7
```

Which is the expected result. It seems like the data is being feed in some bad way.. dunno

**Comment by emoon** [comment]
I don't think you have a bad ROM. It seems more to be the case that either the m68k backend is behaving bad depending on how the input is feed or that it returns back the wrong size (which seems weird as it works fine when I try this is the capstone example code)

**Comment by radare** [comment]
can you paste your capstone test?

**Comment by emoon** [comment]
The only thing I did was to change the ```tests/test_m68k.c```

```C
#define M68K_CODE "\x60\x00\x03\x0a\x4f\xf9\x00\xff\xff\xf0"
```

And also comment out the line

```
print_insn_detail(&insn[j]);
```

Because the example code has a bug in it (but the real printer code does what it should)

**Comment by radare** [comment]
something im worried about the capstone output is that offsets are not padded with zeros so it makes ugly to read. compare this:

```
e asm.bits=32
wx 6000030a4ff900fffff0
?e GNU
e asm.arch=mips.gnu
pd 1
?e CS
e asm.arch=mips
pd 1
```

output:
```
        ,=< 0x00000000      6000030a       j 0x080c0180
        ,=< 0x00000000      6000030a       j 0x80c0180
```

the second is capstone and it looks wrong to me

**Comment by radare** [comment]
also i can point you to over 9000 instructions that gnu disassembles as valid mips instructions and capstone recognizes them as invalid. for example: ff00f94f or 0000f0ff and many others

**Comment by radare** [comment]
ok, using asm.bits=64, makes capstone happy with those instructions

**Comment by radare** [comment]
nevermind, i confused the issue. i have found the bug and ill push the fix soon

**Comment by emoon** [comment]
Sweet! :+1:

**Comment by radare** [comment]
@emoon what do you think about the 0x%08x instead of 0x%x for jmp/call numbers?

**Comment by emoon** [comment]
0x%08x would likely be better yes

**Comment by radare** [comment]
Can you submit the change in capstone master?

**Comment by emoon** [comment]
Now when I think about it this will actually require some more work. Right now the m68k backend doesn't put instructions into instruction groups the code doesn't actually know if it's printing a immediate for a jump or not.

I guess it would be possible to do it anyway but it would be a bit hacky which I would prefer not to do so implementing instruction groups would be the first

Also I have no submit access on capstone (and the work isn't on master yet only in the "next" branch)

**Comment by Maijin** [comment]
r2 uses next no worries.

**Comment by radare** [comment]
the r2 disasembler removes the ‘#’ from the disassembled instructions to make it consistent with the rest of architectures and simplify reading and parsing. afaik there’s no real issue in removing it, isnt? is there any instruction with the same name that any of the arguments can be an immediate or an address and generates different opcode?

**Comment by emoon** [comment]
I'm confused. I thought the issue was to change from ```jmp 0xff``` to ```jmp 0x000000ff``` ?

**Comment by radare** [comment]
Yes it is

**Comment by emoon** [comment]
Alright I will take a look at (can't do it right now but hopefully in not that long time)

**Comment by radare** [comment]
👍

**Comment by cr1901** [comment]
I'm sorry, I haven't had time to follow up on this; I didn't lose interest :P. So the bug is somewhere in the m68k backend returning wrong instruction sizes and/or wrong opcodes?

**Comment by radare** [comment]
Dont think so. This is just related to how the disassembled string is composed and afaik it should be working, but i should review it again

**Comment by cr1901** [comment]
Nope. Same results with commit: aee231ec (Am omitting output b/c it's identical).

**Comment by radare** [comment]
@emoon did you get a chance to look at it?

**Comment by emoon** [comment]
Sorry I haven't had time to look at it yet. Will try to get it done as soon as I can.

**Comment by emoon** [comment]
First part of this is in this PR https://github.com/aquynh/capstone/pull/625 (this doesn't actually fix the printing but adds groups which will make it possible/easier to change the printing according to group (always print full ```%08x``` when there is a branch instruction and an immediate value)

**Comment by radare** [comment]
Good!

**Comment by emoon** [comment]
I will wait until this PR is accepted (hopefully soon) and do the instruction printing in another PR after it.

**Comment by radare** [comment]
For me those tests are passing.. 

```
$ t.asm/m68k/m68k
[OK]  1  m68k: : m68k filter
[OK]  2  m68k: : m68k filter2
[OK]  3  m68k: : m68k.cs filter
[OK]  4  m68k: : m68k.cs filter2
[OK]  5  m68k: : m68k 8bit negative branch
[OK]  6  m68k: : m68k 16bit negative branch bug
[OK]  7  m68k: : m68k 32bit negative branch
```

**Comment by emoon** [comment]
So if the tests are passing what is actually the issue here?

**Comment by cr1901** [comment]
@emoon My issue of symbolic labels not replacing addresses isn't fixed, as shown in the opening post.

**Comment by emoon** [comment]
Right but label replacing is something that is done with radare right and should be independent of the m68k disassembly backend or is radare relying on address to always be fixed width?

**Comment by radare** [comment]
Write a test for your failing test

**Comment by radare** [comment]
Nope, works fine with 0x%x. Open a pr sending the test for your case, so we can properly test all the replacing tests in 1 command

**Comment by radare** [comment]
ping

**Comment by emoon** [comment]
I'm waiting for a basic test-case also so I can fully verify a fix.

**Comment by radare** [comment]
thanks

**Comment by cr1901** [comment]
@radare @emoon I'm sorry, I've been having trouble balancing priorities this month. Can you wait till Sunday for me to create a test case please?

**Comment by emoon** [comment]
@cr1901 sure np!

**Comment by cr1901** [comment]
Test case coming later today. If I'm going to [complain on Twitter](https://twitter.com/cr1901/status/744698323651674112), I should at least do my part :P.

**Comment by emoon** [comment]
Perhaps related to this https://github.com/aquynh/capstone/issues/655

**Comment by radare** [comment]
Works for me https://asciinema.org/a/6y1sqn918y7gfk03k5dqk8scs

the reason why those vars are not replaced is because they dont contain a dot in the name. this is a restriction to avoid having disassembly that replaces addresses by register names and such that will make the code unreadable.

**Comment by radare** [comment]
So this is at the end an issue with bin.smd the plugin that loads megadrive roms. can you provide a test case with an opensource smd rom?

**Comment by Maijin** [comment]
@cr1901  Still waiting

**Comment by cr1901** [comment]
@Maijin @radare Something like this? https://github.com/cr1901/radare2-regressions/blob/master/t.asm/m68k/m68k#L91-L101 (Note: When I run the commands manually in my most recent copy of r2, symbolic label replacement does _not_ occur.)

**Comment by Maijin** [comment]
Is this ROM shareable, if yes make a PR

**Comment by cr1901** [comment]
ROM is shareable; it's already in the regressions repo. I just am not sure I formatted the test correctly. I also think the path is wrong.

**Comment by radare** [comment]
well the reason is because parse.c doesn't replaces more than one immediate. so that should be addressed to close this issue

**Comment by Maijin** [comment]
If I remember this bug was windows problem since I remember you said tests weren't passing on windows but are passing on osx and linux

**Comment by cr1901** [comment]
I think I need to add another test. The regression test I wrote in August (which the bug for that _was_ fixed), is orthogonal to the issue that I opened, _as far as I know_.

**Comment by radare** [comment]
Ok thanks

**Comment by Maijin** [comment]
ping1

**Comment by Svenito** [comment]
Any of the original authors of this thread still around and willing to provide a test case for this?

**Comment by Maijin** [comment]
I did not submit one since the opening 13 Mar 2016, closing.

**Comment by cr1901** [comment]
>Any of the original authors of this thread still around and willing to provide a test case for this?
No time to work on it, but at the very least I'm alive. I'm not even sure what the real issue is at this point (I cannot dup on Linux), so closing is prob for the best now.

If I have time, it'll get a patch for Windows. But way too many of the regression tests on Windows are currently broken for me to consider worth adding it.
